app = "medikalai"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  HOST = "0.0.0.0"
  PORT = "8080"
  FLASK_DEBUG = "0"
  FLASK_ENV = "production"
  SECRET_KEY = "production-secret-key-change-this"
  JWT_SECRET_KEY = "production-jwt-secret-change-this"

[[mounts]]
  source = "medikalai_data"
  destination = "/data"
  
[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 