# fly.toml app configuration file
app = "medikalai"
primary_region = "fra"  # Frankfurt, Almanya

[build]
  dockerfile = "Dockerfile.simple"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  FLASK_DEBUG = "0"  # Canlı ortamda debug kapalı olmalı
  PYTHONUNBUFFERED = "1"  # Python çıktısını anında göndermek için
  PYTHONDONTWRITEBYTECODE = "1"  # .pyc dosyalarını oluşturmamak için

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

# Daha toleranslı health check için - yolu değiştirdik
[checks]
  [checks.http_health]
    grace_period = "180s"
    interval = "30s"
    method = "GET"
    path = "/login"  # Login sayfasını kontrol et
    port = 8080
    timeout = "15s"
    type = "http"
    restart_limit = 5

[deploy]
  release_command = "python -c 'from app import init_db; init_db()'"

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 