# fly.toml app configuration file
app = "medikalai"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

# Daha toleranslı health check için
[checks]
  [checks.http_health]
    grace_period = "120s"
    interval = "30s"
    method = "GET"
    path = "/"
    port = 8080
    timeout = "10s"
    type = "http"
    restart_limit = 5

[deploy]
  release_command = "python -c 'from app import init_db; init_db()'"

[mounts]
  source = "data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 