version: '3.8'

services:
  medikalai:
    build:
      context: .
      dockerfile: Dockerfile.simple  # Basit Dockerfile'覺 kullan
    container_name: medikalai
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - medikalai_data:/data
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      # API anahtarlar覺 environment variable'lar覺ndan al覺nacak
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  medikalai_data:
    name: medikalai_data 